version: "3"
services:
  portal:
    build:
      context: ./portal
    ports:
      - "8080:80"
    environment:
      DB_URL: mariadb
      DB_USER: root
      DB_PASSWORD: p455w0rdF0rDb
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: p455w0rdF0rDb
    volumes:
      - ./portal/sql:/docker-entrypoint-initdb.d:ro
